spring:
  application:
    name: Ticket_System
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

cors:
  frontend:
    url: ${CORS_FRONTEND_URL}

jwt:
  access:
    expiration:
      time: ${JWT_ACCESS_EXPIRATION_TIME}
  refresh:
    expiration:
      time: ${JWT_REFRESH_EXPIRATION_TIME}
  secret:
    key: ${JWT_ SECRET_KEY}

ngRok:
  url: ${NGROK_URL}
#springdoc:
#  swagger-ui:
#    config-url: https://28a654e177bd.ngrok-free.app/swagger-ui/index.html#